name: user service build
on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build and Test
    needs: sast
    uses: https://github.com/Rahul-Bristlecone/user-account-service.git/.github/workflows/reusable-ci.yaml
    with:
      service-name: user-service
      docker-repo: daemons
      target-environment: production
    secrets: inherit